"""Add ondelete cascade to training_question.material_id

Revision ID: 04c0feeb3bf9
Revises: 92673b93d1ba
Create Date: 2025-06-21 16:14:42.975018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c0feeb3bf9'
down_revision = '92673b93d1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('training_question_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_material', ['material_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('training_question_ibfk_2'), 'training_material', ['material_id'], ['id'])

    # ### end Alembic commands ###
