"""Add ondelete cascade to training_task.material_id

Revision ID: 6eea8c134982
Revises: 04c0feeb3bf9
Create Date: 2025-06-21 16:26:32.649102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6eea8c134982'
down_revision = '04c0feeb3bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_task', schema=None) as batch_op:
        batch_op.alter_column('material_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('training_task_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_material', ['material_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('training_task_ibfk_2'), 'training_material', ['material_id'], ['id'])
        batch_op.alter_column('material_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
