"""Add md5 field to training_material table

Revision ID: 92673b93d1ba
Revises: 
Create Date: 2025-06-19 09:37:43.382757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92673b93d1ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('md5', sa.String(length=32), nullable=False))
        batch_op.create_unique_constraint(None, ['md5'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_material', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('md5')

    # ### end Alembic commands ###
