version: "3.8"
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: qxt-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  web:
    build: ./app
    container_name: qxt-web
    command: python app.py
    environment:
      - FLASK_ENV=development
      - TZ=Asia/Shanghai
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5050:5050"
    volumes:
      - ./app:/app
      - ./app/static:/app/static
      - ./app/templates:/app/templates
    depends_on:
      - db
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: myadmin
    environment:
      PMA_HOST: db # 注意这里用 db（就是上面的服务名），不是qxt-mysql
      TZ: Asia/Shanghai
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

volumes:
  mysql_data:
